import './globals.css';
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReduxProvider } from './redux/provider';
import App from '@/App';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Letr Ladr',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en" className={inter.className}>
      <ReduxProvider>
        <App>
          {children}
        </App>
      </ReduxProvider>
    </html>
  );
}
